name: CI

on: [push, pull_request]

jobs:
  jammy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: APT=1 CI=1 MKJOBS=2 ./src/tools/ci.sh
  noble:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: APT=1 CI=1 MKJOBS=2 ./src/tools/ci.sh
